-- ============================================================================
-- CENTRO DE MONITOREO SSSUR — Esquema Definitivo v4
-- Motor: Supabase / PostgreSQL + PostGIS
-- Alcance: Sistema interno (admin + empleados) con extensión preparada
--          para portal ciudadano futuro.
--
-- Fusiona:
--   · Esquema operativo del sistema AppSheet original (AppSheet → SQL)
--   · Estándar Supabase con auth.users y RLS
--   · Permisos granulares CRUD por módulo (matriz admin)
--   · Impersonación de usuarios para soporte técnico (superadmin)
--   · Estados de caso personalizables por categoría
--   · Noticias municipales con trazados geoespaciales
--   · Jerarquía de casos (caso_padre_id para vincular denuncia → tarea)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. EXTENSIONES
-- ----------------------------------------------------------------------------
create extension if not exists "pgcrypto";
create extension if not exists "postgis";
create extension if not exists "citext";

-- ============================================================================
-- BLOQUE 1: TERRITORIO Y ESTRUCTURA ADMINISTRATIVA
-- ============================================================================

create table public.municipios (
    id          smallint generated by default as identity primary key,
    codigo      text not null unique,
    nombre      text not null unique,
    activo      boolean not null default true,
    created_at  timestamptz not null default now()
);

create table public.distritos (
    id            smallint generated by default as identity primary key,
    municipio_id  smallint not null references public.municipios(id),
    codigo        text not null,
    nombre        text not null,
    activo        boolean not null default true,
    created_at    timestamptz not null default now(),
    unique (municipio_id, codigo),
    unique (municipio_id, nombre)
);

comment on table public.distritos is
    'Distritos/municipios que componen el territorio de SSSur. '
    'Panchimalco, Rosario de Mora, San Marcos, Santiago Texacuangos, Santo Tomás.';

create table public.direcciones_administrativas (
    id          bigint generated always as identity primary key,
    codigo      text not null unique,
    nombre      text not null unique,
    activo      boolean not null default true,
    created_at  timestamptz not null default now()
);

comment on table public.direcciones_administrativas is
    'Nivel gerencial superior (ej. "Dirección de Servicios y Obras Municipales").';

create table public.departamentos (
    id              bigint generated always as identity primary key,
    direccion_id    bigint not null references public.direcciones_administrativas(id),
    jefe_usuario_id uuid,                    -- FK diferida: se completa al crear usuarios
    codigo          text not null unique,
    nombre          text not null,
    estado          text not null default 'activo'
                    check (estado in ('activo', 'inactivo')),
    created_at      timestamptz not null default now(),
    unique (direccion_id, nombre)
);

comment on column public.departamentos.jefe_usuario_id is
    'FK a usuarios.id. Se define post-creación para evitar dependencia circular.';

-- ============================================================================
-- BLOQUE 2: SEGURIDAD — ROLES, PERMISOS CRUD Y USUARIOS
-- ============================================================================

-- ------------------------------------
-- 2.1 Roles del sistema
-- ------------------------------------
create table public.roles (
    id            bigint generated always as identity primary key,
    codigo        text not null unique,
    nombre        text not null unique,
    descripcion   text,
    es_sistema    boolean not null default false,   -- Si true, no se puede eliminar
    activo        boolean not null default true,
    created_at    timestamptz not null default now()
);

comment on column public.roles.es_sistema is
    'Roles protegidos (superadmin, admin, empleado_campo) que no pueden borrarse desde la UI.';

-- ------------------------------------
-- 2.2 Módulos y permisos CRUD
-- Cada módulo tiene flags Ver, Crear, Editar, Borrar, Exportar.
-- Esto refleja la matriz visual del panel "Roles y Permisos" del admin.
-- ------------------------------------
create table public.permisos_modulos (
    id              bigint generated always as identity primary key,
    codigo_modulo   text not null unique,      -- Ej: 'casos', 'usuarios', 'reportes'
    nombre_modulo   text not null,
    descripcion     text,
    activo          boolean not null default true
);

comment on table public.permisos_modulos is
    'Catálogo de módulos del sistema. Cada fila representa un módulo en la matriz de permisos.';

-- Tabla de asignación rol → módulo con bits CRUD explícitos
create table public.roles_permisos (
    id                  bigint generated always as identity primary key,
    rol_id              bigint not null references public.roles(id) on delete cascade,
    permiso_modulo_id   bigint not null references public.permisos_modulos(id) on delete cascade,
    ver                 boolean not null default false,
    crear               boolean not null default false,
    editar              boolean not null default false,
    borrar              boolean not null default false,
    exportar            boolean not null default false,
    created_at          timestamptz not null default now(),
    unique (rol_id, permiso_modulo_id)
);

comment on table public.roles_permisos is
    'Matriz rol × módulo con permisos CRUD explícitos. '
    'Una fila por combinación rol+módulo. Visualizable como tabla de checkboxes en el admin.';

-- ------------------------------------
-- 2.3 Usuarios institucionales
-- ------------------------------------
create table public.usuarios (
    id                  uuid primary key references auth.users(id) on delete cascade,
    username            citext unique,
    email_institucional citext unique,
    nombres             text not null,
    apellidos           text not null,
    dui                 text unique,           -- DUI para identificación formal
    telefono            text,
    foto_perfil_url     text,
    puesto_cargo        text,
    departamento_id     bigint references public.departamentos(id),
    distrito_id         smallint references public.distritos(id),
    rol_id              bigint references public.roles(id),
    cuadrilla_id        bigint,                -- FK diferida hasta crear cuadrillas
    activo              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

comment on column public.usuarios.id is
    'Sincronizado con auth.users.id de Supabase Auth.';

-- FK circular: departamentos.jefe_usuario_id → usuarios.id
alter table public.departamentos
    add constraint fk_dpto_jefe
    foreign key (jefe_usuario_id)
    references public.usuarios(id)
    deferrable initially deferred;

-- ------------------------------------
-- 2.4 Cuadrillas (equipos operativos)
-- ------------------------------------
create table public.cuadrillas (
    id               bigint generated always as identity primary key,
    departamento_id  bigint not null references public.departamentos(id),
    codigo           text not null unique,
    nombre           text not null,
    activo           boolean not null default true,
    created_at       timestamptz not null default now()
);

create table public.cuadrilla_integrantes (
    cuadrilla_id     bigint not null references public.cuadrillas(id) on delete cascade,
    usuario_id       uuid not null references public.usuarios(id) on delete cascade,
    es_lider         boolean not null default false,
    assigned_at      timestamptz not null default now(),
    primary key (cuadrilla_id, usuario_id)
);

-- Completar FK diferida de usuarios.cuadrilla_id
alter table public.usuarios
    add constraint fk_usuario_cuadrilla
    foreign key (cuadrilla_id)
    references public.cuadrillas(id)
    deferrable initially deferred;

-- ------------------------------------
-- 2.5 Ciudadanos (portal futuro, prep.)
-- ------------------------------------
create table public.ciudadanos (
    id          uuid primary key references auth.users(id) on delete cascade,
    dui         text unique,
    telefono    text,
    nombres     text not null,
    apellidos   text not null,
    distrito_id smallint references public.distritos(id),
    activo      boolean not null default true,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

comment on table public.ciudadanos is
    'Ciudadanos registrados en el portal de población (futuro). '
    'Separados de la tabla usuarios para no mezclar accesos institucionales con acceso público.';

-- ------------------------------------
-- 2.6 Impersonación de usuarios (soporte superadmin)
-- ------------------------------------
create table public.sesiones_impersonacion (
    id                      bigint generated always as identity primary key,
    superadmin_id           uuid not null references public.usuarios(id),
    usuario_impersonado_id  uuid not null references public.usuarios(id),
    motivo_soporte          text not null,
    fecha_inicio            timestamptz not null default now(),
    fecha_fin               timestamptz,
    ip_origen               text,
    token_sesion            text,
    check (superadmin_id <> usuario_impersonado_id)
);

comment on table public.sesiones_impersonacion is
    'Registro de sesiones donde el superadmin tomó control de la sesión de otro usuario '
    'para dar soporte o validar flujos. Toda acción realizada bajo impersonación se registra '
    'en bitacora_auditoria con fue_impersonado=true.';

-- ============================================================================
-- BLOQUE 3: CATÁLOGOS OPERATIVOS
-- ============================================================================

create table public.prioridades (
    id                      smallint primary key,
    codigo                  text not null unique,
    nombre                  text not null,
    nivel                   smallint not null unique check (nivel between 1 and 5),
    color_hex               text,
    tiempo_objetivo_horas   integer
);

create table public.canales_reporte (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,           -- Ej: 'App Móvil', 'Presencial', 'Call Center'
    activo      boolean not null default true
);

-- ------------------------------------
-- 3.1 Categorías de casos CON estados personalizados por categoría
-- El frontend (estados-denuncias.js) muestra que cada categoría tiene
-- su propio flujo de estados (Alumbrado ≠ Baches ≠ CAM).
-- Esto se resuelve guardando los estados como JSONB dentro del catálogo.
-- ------------------------------------
create table public.categorias_caso (
    id                          bigint generated always as identity primary key,
    codigo                      text not null unique,
    nombre                      text not null,
    descripcion                 text,
    icono                       text,
    color_hex                   text,
    departamento_responsable_id bigint not null references public.departamentos(id),
    prioridad_default_id        smallint references public.prioridades(id),
    requiere_ubicacion          boolean not null default true,
    -- Flujo de estados propio de esta categoría.
    -- Formato: [{"id":"recibida","nombre":"Recibida","icono":"fa-inbox","color":"gray","es_final":false}, ...]
    estados_flujo               jsonb not null default '[]'::jsonb,
    estado_inicial              text,    -- id del estado con el que nace un caso de esta categoría
    activo                      boolean not null default true,
    created_at                  timestamptz not null default now()
);

comment on column public.categorias_caso.estados_flujo is
    'Array JSON de estados posibles para casos de esta categoría. '
    'Permite que Alumbrado Público tenga estados distintos a Baches o CAM, '
    'replicando el comportamiento de assets/js/utils/estados-denuncias.js.';

comment on column public.categorias_caso.estado_inicial is
    'Código del primer estado en estados_flujo al crear un caso. Ej: "recibida".';

-- ============================================================================
-- BLOQUE 4: NÚCLEO OPERATIVO — CASOS (tabla única con jerarquía)
-- ============================================================================

create table public.casos (
    id                          bigint generated always as identity primary key,
    -- Jerarquía: una tarea de campo puede ser hija de un caso padre (denuncia)
    caso_padre_id               bigint references public.casos(id) on delete set null,
    categoria_id                bigint not null references public.categorias_caso(id),
    distrito_id                 smallint not null references public.distritos(id),
    canal_reporte_id            smallint not null references public.canales_reporte(id),
    departamento_actual_id      bigint not null references public.departamentos(id),

    -- Creación: o usuario institucional o ciudadano (no ambos)
    creado_por_usuario_id       uuid references public.usuarios(id),
    creado_por_ciudadano_id     uuid references public.ciudadanos(id),

    -- Asignación
    usuario_responsable_id      uuid references public.usuarios(id),
    cuadrilla_responsable_id    bigint references public.cuadrillas(id),

    -- Estado: código del estado según el flujo de la categoría (no FK, es libre)
    estado_codigo               text not null default 'recibida',
    prioridad_id                smallint not null references public.prioridades(id),

    -- Datos del caso
    correlativo                 text unique,
    titulo                      text not null,
    descripcion                 text not null check (char_length(descripcion) between 10 and 2000),
    direccion_referencia        text not null check (char_length(direccion_referencia) between 5 and 300),
    ubicacion                   geography(Point, 4326),
    resolucion                  text,           -- Descripción de resolución al cerrar el caso

    -- Fechas de ciclo de vida
    fecha_recibido              timestamptz,
    fecha_asignado              timestamptz,
    fecha_cierre                timestamptz,
    observaciones_internas      text,

    -- Auditoría
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now(),
    deleted_at                  timestamptz,

    -- Restricciones
    constraint ck_casos_creador check (
        (creado_por_usuario_id is not null and creado_por_ciudadano_id is null)
        or
        (creado_por_ciudadano_id is not null and creado_por_usuario_id is null)
    ),
    constraint ck_casos_bbox_sssur check (
        ubicacion is null or (
            st_y(ubicacion::geometry) between 13.50 and 13.85
            and st_x(ubicacion::geometry) between -89.40 and -89.05
        )
    )
);

comment on column public.casos.caso_padre_id is
    'Referencia al caso padre. Permite que una tarea de intervención (empleado) '
    'esté vinculada a la denuncia original que la generó.';

comment on column public.casos.estado_codigo is
    'Código del estado actual según el flujo definido en categorias_caso.estados_flujo. '
    'No es FK para mantener la flexibilidad de estados por categoría.';

comment on column public.casos.resolucion is
    'Descripción de cierre escrita por el empleado en la vista "Cierre de Incidente". '
    'Es pública y puede incluirse en el comprobante para el ciudadano.';

-- Índices
create index idx_casos_categoria    on public.casos (categoria_id);
create index idx_casos_distrito     on public.casos (distrito_id);
create index idx_casos_departamento on public.casos (departamento_actual_id);
create index idx_casos_estado       on public.casos (estado_codigo);
create index idx_casos_padre        on public.casos (caso_padre_id);
create index idx_casos_responsable  on public.casos (usuario_responsable_id);
create index idx_casos_cuadrilla    on public.casos (cuadrilla_responsable_id);
create index idx_casos_created_at   on public.casos (created_at desc);
create index idx_casos_ubicacion    on public.casos using gist (ubicacion);

-- ------------------------------------
-- 4.1 Adjuntos del caso
-- ------------------------------------
create table public.casos_adjuntos (
    id                  bigint generated always as identity primary key,
    caso_id             bigint not null references public.casos(id) on delete cascade,
    tipo_archivo        text not null check (tipo_archivo in ('foto', 'video', 'audio', 'documento')),
    es_evidencia        boolean not null default false,   -- false=referencia inicial, true=evidencia de cierre
    url_supabase        text not null,
    url_backup          text,                              -- URL de backup en cPanel si la foto fue purgada
    nombre_archivo      text,
    mime_type           text,
    tamano_bytes        bigint,
    hash_sha256         text,
    created_at          timestamptz not null default now()
);

comment on column public.casos_adjuntos.es_evidencia is
    'false: foto de referencia al reportar. true: evidencia fotográfica de resolución al cerrar.';

-- ------------------------------------
-- 4.2 Historial de estados del caso
-- ------------------------------------
create table public.historial_estados_caso (
    id                      bigint generated always as identity primary key,
    caso_id                 bigint not null references public.casos(id) on delete cascade,
    estado_codigo_anterior  text,
    estado_codigo_nuevo     text not null,
    cambiado_por_usuario_id uuid references public.usuarios(id),
    fue_impersonado         boolean not null default false,
    superadmin_real_id      uuid references public.usuarios(id),
    observacion             text,
    created_at              timestamptz not null default now()
);

-- ------------------------------------
-- 4.3 Derivaciones entre departamentos
-- ------------------------------------
create table public.casos_derivaciones (
    id                      bigint generated always as identity primary key,
    caso_id                 bigint not null references public.casos(id) on delete cascade,
    departamento_origen_id  bigint references public.departamentos(id),
    departamento_destino_id bigint not null references public.departamentos(id),
    derivado_por_usuario_id uuid not null references public.usuarios(id),
    motivo                  text,
    created_at              timestamptz not null default now()
);

-- ============================================================================
-- BLOQUE 5: NOTICIAS MUNICIPALES (Portal Población)
-- ============================================================================

create table public.noticias (
    id              bigint generated always as identity primary key,
    titulo          text not null,
    categoria       text not null,             -- Ej: 'Vialidad', 'Emergencias', 'Servicios'
    categoria_color text,
    categoria_icono text,
    descripcion     text not null,
    -- Para noticias tipo "cierre de vía", almacena las coordenadas del trazado
    trazado_geojson jsonb,                     -- Array de [lat, lng] pares
    ubicacion       geography(Point, 4326),    -- Punto de referencia de la noticia
    autor           text,
    autor_icono     text,
    imagen_url      text,
    publicada_por_id uuid references public.usuarios(id),
    activa          boolean not null default true,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

comment on table public.noticias is
    'Avisos y noticias publicadas exclusivamente por la alcaldía. '
    'Visibles en la vista "Noticias" del portal ciudadano, '
    'filtradas por los distritos del ciudadano registrado.';

comment on column public.noticias.trazado_geojson is
    'Coordenadas del trazado geoespacial para noticias tipo cierre de vía. '
    'Se renderiza como polyline en el mapa del portal ciudadano.';

-- Relación muchos-a-muchos: una noticia puede aplicar a múltiples distritos
create table public.noticias_distritos (
    noticia_id   bigint not null references public.noticias(id) on delete cascade,
    distrito_id  smallint not null references public.distritos(id) on delete cascade,
    primary key (noticia_id, distrito_id)
);

-- ============================================================================
-- BLOQUE 6: DOCUMENTOS Y PLANTILLAS DE REPORTES
-- ============================================================================

create table public.plantillas_documento (
    id                  bigint generated always as identity primary key,
    codigo              text not null unique,
    nombre              text not null,
    tipo_formato        text not null check (tipo_formato in ('pdf', 'xlsx')),
    tipo_uso            text not null,   -- 'comprobante_denuncia', 'reporte_general', 'informe_intervencion'
    departamento_id     bigint references public.departamentos(id),   -- null = aplica a todo el sistema
    categoria_id        bigint references public.categorias_caso(id), -- null = general del departamento
    descripcion         text,
    es_oficial          boolean not null default true,
    activa              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

comment on column public.plantillas_documento.departamento_id is
    'NULL si la plantilla es transversal a todo el sistema.';

comment on column public.plantillas_documento.categoria_id is
    'NULL si la plantilla aplica a todo el departamento. '
    'Con valor, aplica solo a esa categoría específica (ej: solo para Alumbrado Público).';

create table public.plantillas_versiones (
    id                      bigint generated always as identity primary key,
    plantilla_id            bigint not null references public.plantillas_documento(id) on delete cascade,
    version_numero          integer not null,
    es_vigente              boolean not null default false,
    contenido_html          text,        -- Template HTML para renders PDF
    esquema_excel_json      text,        -- Estructura/mapeo de celdas para exports XLSX
    creado_por_usuario_id   uuid references public.usuarios(id),
    created_at              timestamptz not null default now(),
    unique (plantilla_id, version_numero)
);

create unique index uq_plantilla_version_vigente
on public.plantillas_versiones (plantilla_id)
where es_vigente = true;

create table public.documentos_emitidos (
    id                      bigint generated always as identity primary key,
    plantilla_id            bigint references public.plantillas_documento(id),
    plantilla_version_id    bigint references public.plantillas_versiones(id),
    caso_id                 bigint references public.casos(id) on delete cascade,
    generado_por_usuario_id uuid references public.usuarios(id),
    tipo_documento          text not null check (tipo_documento in ('pdf', 'xlsx')),
    nombre_archivo          text not null,
    url_supabase            text,
    parametros_filtros      jsonb not null default '{}'::jsonb,   -- Rango de fechas, estados, etc.
    hash_sha256             text,
    created_at              timestamptz not null default now()
);

comment on column public.documentos_emitidos.caso_id is
    'NULL si es un reporte consolidado general, no vinculado a un caso específico.';

-- ============================================================================
-- BLOQUE 7: AUDITORÍA
-- ============================================================================

create table public.bitacora_auditoria (
    id                      bigint generated always as identity primary key,
    usuario_id              uuid references public.usuarios(id),
    fue_impersonado         boolean not null default false,
    superadmin_real_id      uuid references public.usuarios(id),
    accion                  text not null,       -- INSERT, UPDATE, DELETE, LOGIN, EXPORT, IMPERSONATE
    tabla_afectada          text not null,
    registro_id             text,
    valores_anteriores      jsonb,
    valores_nuevos          jsonb,
    ip_cliente              text,
    created_at              timestamptz not null default now()
);

comment on column public.bitacora_auditoria.fue_impersonado is
    'true si la acción fue ejecutada por un superadmin impersonando a otro usuario.';

comment on column public.bitacora_auditoria.superadmin_real_id is
    'ID del superadmin real que ejecutó la acción bajo impersonación.';

-- ============================================================================
-- BLOQUE 8: FUNCIONES Y TRIGGERS
-- ============================================================================

-- ------------------------------------
-- 8.1 updated_at automático
-- ------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger trg_usuarios_updated_at
    before update on public.usuarios
    for each row execute function public.set_updated_at();

create trigger trg_casos_updated_at
    before update on public.casos
    for each row execute function public.set_updated_at();

create trigger trg_noticias_updated_at
    before update on public.noticias
    for each row execute function public.set_updated_at();

create trigger trg_plantillas_updated_at
    before update on public.plantillas_documento
    for each row execute function public.set_updated_at();

-- ------------------------------------
-- 8.2 Sincronizar campos al crear un caso
-- ------------------------------------
create or replace function public.sincronizar_campos_caso()
returns trigger language plpgsql as $$
declare
    v_departamento_id bigint;
    v_prioridad_id    smallint;
    v_estado_inicial  text;
begin
    -- Obtener defaults de la categoría
    select c.departamento_responsable_id, c.prioridad_default_id, c.estado_inicial
    into v_departamento_id, v_prioridad_id, v_estado_inicial
    from public.categorias_caso c
    where c.id = new.categoria_id;

    -- Aplicar defaults si no se proporcionaron
    if new.departamento_actual_id is null then
        new.departamento_actual_id = v_departamento_id;
    end if;
    if new.prioridad_id is null then
        new.prioridad_id = coalesce(v_prioridad_id, 3);
    end if;
    if new.estado_codigo is null or new.estado_codigo = '' then
        new.estado_codigo = coalesce(v_estado_inicial, 'recibida');
    end if;
    if new.correlativo is null then
        new.correlativo = 'CASO-' || extract(year from now())::text
                         || '-' || lpad(new.id::text, 6, '0');
    end if;

    return new;
end;
$$;

create trigger trg_casos_sync_campos
    before insert on public.casos
    for each row execute function public.sincronizar_campos_caso();

-- ------------------------------------
-- 8.3 Derivación actualiza departamento_actual del caso
-- ------------------------------------
create or replace function public.aplicar_derivacion_caso()
returns trigger language plpgsql as $$
begin
    update public.casos
    set departamento_actual_id = new.departamento_destino_id,
        updated_at = now()
    where id = new.caso_id;
    return new;
end;
$$;

create trigger trg_derivaciones_caso
    after insert on public.casos_derivaciones
    for each row execute function public.aplicar_derivacion_caso();

-- ------------------------------------
-- 8.4 Auditoría automática por trigger
-- ------------------------------------
create or replace function public.registrar_auditoria()
returns trigger language plpgsql security definer as $$
declare
    v_superadmin_id uuid;
    v_fue_impersonado boolean := false;
begin
    -- Detectar si la sesión actual es una impersonación activa
    select si.superadmin_id into v_superadmin_id
    from public.sesiones_impersonacion si
    where si.usuario_impersonado_id = auth.uid()
      and si.fecha_fin is null
    limit 1;

    if v_superadmin_id is not null then
        v_fue_impersonado := true;
    end if;

    insert into public.bitacora_auditoria
        (usuario_id, fue_impersonado, superadmin_real_id, accion, tabla_afectada, registro_id, valores_anteriores, valores_nuevos)
    values (
        auth.uid(),
        v_fue_impersonado,
        v_superadmin_id,
        TG_OP,
        TG_TABLE_NAME,
        coalesce(new.id, old.id)::text,
        case when TG_OP = 'DELETE' then to_jsonb(old) else null end,
        case when TG_OP <> 'DELETE' then to_jsonb(new) else null end
    );
    return coalesce(new, old);
end;
$$;

create trigger trg_auditoria_casos
    after insert or update or delete on public.casos
    for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_usuarios
    after insert or update or delete on public.usuarios
    for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_plantillas
    after insert or update or delete on public.plantillas_versiones
    for each row execute function public.registrar_auditoria();

-- ============================================================================
-- BLOQUE 9: FUNCIONES DE UTILIDAD PARA RLS
-- ============================================================================

-- Verificar si el usuario autenticado tiene un rol específico
create or replace function public.auth_tiene_rol(p_rol_codigo text)
returns boolean language sql security definer stable as $$
    select exists (
        select 1
        from public.usuarios u
        join public.roles r on r.id = u.rol_id
        where u.id = auth.uid()
          and u.activo = true
          and r.activo = true
          and r.codigo = p_rol_codigo
    );
$$;

-- Verificar si el usuario tiene un permiso específico (por bits CRUD)
create or replace function public.auth_tiene_permiso(p_modulo text, p_accion text)
returns boolean language sql security definer stable as $$
    select case p_accion
        when 'ver'      then bool_or(rp.ver)
        when 'crear'    then bool_or(rp.crear)
        when 'editar'   then bool_or(rp.editar)
        when 'borrar'   then bool_or(rp.borrar)
        when 'exportar' then bool_or(rp.exportar)
        else false
    end
    from public.usuarios u
    join public.roles_permisos rp on rp.rol_id = u.rol_id
    join public.permisos_modulos pm on pm.id = rp.permiso_modulo_id
    where u.id = auth.uid()
      and u.activo = true
      and pm.codigo_modulo = p_modulo
      and pm.activo = true;
$$;

comment on function public.auth_tiene_permiso is
    'Uso: auth_tiene_permiso(''casos'', ''crear'') — '
    'Verifica el bit específico de la matriz CRUD para el usuario autenticado.';

-- Obtener el distrito del usuario autenticado (para filtros RLS)
create or replace function public.auth_distrito_id()
returns smallint language sql security definer stable as $$
    select distrito_id from public.usuarios where id = auth.uid();
$$;

-- ============================================================================
-- BLOQUE 10: VISTAS ÚTILES PARA EL FRONTEND
-- ============================================================================

-- Vista del mapa: casos con coordenadas y metadatos para pines
create view public.v_casos_mapa as
select
    c.id,
    c.correlativo,
    c.titulo,
    c.descripcion,
    c.estado_codigo,
    c.prioridad_id,
    p.nombre       as prioridad_nombre,
    p.color_hex    as prioridad_color,
    c.categoria_id,
    cat.nombre     as categoria_nombre,
    cat.icono      as categoria_icono,
    cat.color_hex  as categoria_color,
    c.distrito_id,
    d.nombre       as distrito_nombre,
    c.departamento_actual_id,
    dep.nombre     as departamento_nombre,
    case when c.ubicacion is null then null
         else st_y(c.ubicacion::geometry) end as lat,
    case when c.ubicacion is null then null
         else st_x(c.ubicacion::geometry) end as lng,
    c.caso_padre_id,
    c.created_at,
    c.updated_at
from public.casos c
join public.distritos d on d.id = c.distrito_id
join public.prioridades p on p.id = c.prioridad_id
join public.categorias_caso cat on cat.id = c.categoria_id
join public.departamentos dep on dep.id = c.departamento_actual_id
where c.deleted_at is null;

-- Vista para el panel de empleados: mis intervenciones
create view public.v_mis_intervenciones as
select
    c.id,
    c.correlativo,
    c.titulo,
    c.descripcion,
    c.estado_codigo,
    c.prioridad_id,
    p.color_hex    as prioridad_color,
    cat.nombre     as categoria_nombre,
    cat.icono      as categoria_icono,
    cat.color_hex  as categoria_color,
    cat.estados_flujo,
    d.nombre       as distrito_nombre,
    c.fecha_recibido,
    c.fecha_asignado,
    case when c.ubicacion is null then null
         else st_y(c.ubicacion::geometry) end as lat,
    case when c.ubicacion is null then null
         else st_x(c.ubicacion::geometry) end as lng,
    c.direccion_referencia,
    c.caso_padre_id,
    c.usuario_responsable_id,
    c.cuadrilla_responsable_id
from public.casos c
join public.distritos d on d.id = c.distrito_id
join public.prioridades p on p.id = c.prioridad_id
join public.categorias_caso cat on cat.id = c.categoria_id
where c.deleted_at is null;

comment on view public.v_mis_intervenciones is
    'Vista usada por la PWA de empleados para mostrar los casos asignados. '
    'Incluye estados_flujo de la categoría para que el frontend '
    'renderice los botones de avance de estado correctamente.';

-- ============================================================================
-- BLOQUE 11: ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Habilitar RLS en todas las tablas
alter table public.municipios              enable row level security;
alter table public.distritos               enable row level security;
alter table public.direcciones_administrativas enable row level security;
alter table public.departamentos           enable row level security;
alter table public.roles                   enable row level security;
alter table public.permisos_modulos        enable row level security;
alter table public.roles_permisos          enable row level security;
alter table public.usuarios                enable row level security;
alter table public.cuadrillas              enable row level security;
alter table public.cuadrilla_integrantes   enable row level security;
alter table public.ciudadanos              enable row level security;
alter table public.sesiones_impersonacion  enable row level security;
alter table public.prioridades             enable row level security;
alter table public.canales_reporte         enable row level security;
alter table public.categorias_caso         enable row level security;
alter table public.casos                   enable row level security;
alter table public.casos_adjuntos          enable row level security;
alter table public.historial_estados_caso  enable row level security;
alter table public.casos_derivaciones      enable row level security;
alter table public.noticias                enable row level security;
alter table public.noticias_distritos      enable row level security;
alter table public.plantillas_documento    enable row level security;
alter table public.plantillas_versiones    enable row level security;
alter table public.documentos_emitidos     enable row level security;
alter table public.bitacora_auditoria      enable row level security;

-- ------------------------------------
-- Catálogos: lectura libre para autenticados
-- ------------------------------------
create policy "catalogos_select_autenticado"
    on public.municipios for select to authenticated using (true);

create policy "catalogos_select_distritos"
    on public.distritos for select to authenticated using (true);

create policy "catalogos_select_direcciones"
    on public.direcciones_administrativas for select to authenticated using (true);

create policy "catalogos_select_departamentos"
    on public.departamentos for select to authenticated using (true);

create policy "catalogos_select_roles"
    on public.roles for select to authenticated using (true);

create policy "catalogos_select_permisos_modulos"
    on public.permisos_modulos for select to authenticated using (true);

create policy "catalogos_select_roles_permisos"
    on public.roles_permisos for select to authenticated using (true);

create policy "catalogos_select_prioridades"
    on public.prioridades for select to authenticated using (true);

create policy "catalogos_select_canales"
    on public.canales_reporte for select to authenticated using (true);

create policy "catalogos_select_categorias"
    on public.categorias_caso for select to authenticated using (true);

-- Edición de catálogos: solo admin/superadmin
create policy "catalogos_write_admin"
    on public.roles for all to authenticated
    using (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "categorias_write_admin"
    on public.categorias_caso for all to authenticated
    using (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Usuarios
-- ------------------------------------
create policy "usuarios_select_propio_o_admin"
    on public.usuarios for select to authenticated
    using (id = auth.uid() or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "usuarios_insert_admin"
    on public.usuarios for insert to authenticated
    with check (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "usuarios_update_propio_o_admin"
    on public.usuarios for update to authenticated
    using (id = auth.uid() or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (id = auth.uid() or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Casos: acceso por permiso del módulo 'casos'
-- ------------------------------------
create policy "casos_select"
    on public.casos for select to authenticated
    using (public.auth_tiene_permiso('casos', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "casos_insert"
    on public.casos for insert to authenticated
    with check (public.auth_tiene_permiso('casos', 'crear') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "casos_update"
    on public.casos for update to authenticated
    using (
        -- El responsable asignado puede actualizar su caso
        usuario_responsable_id = auth.uid()
        or public.auth_tiene_permiso('casos', 'editar')
        or public.auth_tiene_rol('admin')
        or public.auth_tiene_rol('superadmin')
    )
    with check (
        usuario_responsable_id = auth.uid()
        or public.auth_tiene_permiso('casos', 'editar')
        or public.auth_tiene_rol('admin')
        or public.auth_tiene_rol('superadmin')
    );

create policy "casos_adjuntos_select"
    on public.casos_adjuntos for select to authenticated
    using (public.auth_tiene_permiso('casos', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "casos_adjuntos_write"
    on public.casos_adjuntos for all to authenticated
    using (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "historial_select"
    on public.historial_estados_caso for select to authenticated
    using (public.auth_tiene_permiso('casos', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "historial_write"
    on public.historial_estados_caso for all to authenticated
    using (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "derivaciones_select"
    on public.casos_derivaciones for select to authenticated
    using (public.auth_tiene_permiso('casos', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "derivaciones_write"
    on public.casos_derivaciones for all to authenticated
    using (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_permiso('casos', 'editar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Noticias
-- ------------------------------------
create policy "noticias_select_autenticado"
    on public.noticias for select to authenticated using (activa = true);

create policy "noticias_write_admin"
    on public.noticias for all to authenticated
    using (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "noticias_distritos_select"
    on public.noticias_distritos for select to authenticated using (true);

create policy "noticias_distritos_write_admin"
    on public.noticias_distritos for all to authenticated
    using (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Plantillas y documentos
-- ------------------------------------
create policy "plantillas_select"
    on public.plantillas_documento for select to authenticated
    using (public.auth_tiene_permiso('reportes', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "plantillas_write_superadmin"
    on public.plantillas_documento for all to authenticated
    using (public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('superadmin'));

create policy "plantillas_versiones_select"
    on public.plantillas_versiones for select to authenticated
    using (public.auth_tiene_permiso('reportes', 'ver') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

create policy "plantillas_versiones_write_superadmin"
    on public.plantillas_versiones for all to authenticated
    using (public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('superadmin'));

create policy "documentos_select"
    on public.documentos_emitidos for select to authenticated
    using (
        generado_por_usuario_id = auth.uid()
        or public.auth_tiene_permiso('reportes', 'ver')
        or public.auth_tiene_rol('admin')
        or public.auth_tiene_rol('superadmin')
    );

create policy "documentos_insert"
    on public.documentos_emitidos for insert to authenticated
    with check (public.auth_tiene_permiso('reportes', 'exportar') or public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Impersonación: solo superadmin
-- ------------------------------------
create policy "impersonacion_superadmin"
    on public.sesiones_impersonacion for all to authenticated
    using (public.auth_tiene_rol('superadmin'))
    with check (public.auth_tiene_rol('superadmin'));

-- ------------------------------------
-- Bitácora: solo admins pueden leer
-- ------------------------------------
create policy "bitacora_select_admin"
    on public.bitacora_auditoria for select to authenticated
    using (public.auth_tiene_rol('admin') or public.auth_tiene_rol('superadmin'));

-- ============================================================================
-- FIN DEL ESQUEMA v4
-- ============================================================================
-- Extensiones futuras:
--   - Si se aprueba el portal ciudadano, agregar políticas de RLS para
--     ciudadanos que solo pueden ver sus propios casos (creado_por_ciudadano_id = auth.uid()).
--   - Notificaciones push: agregar tabla push_subscriptions con endpoint, p256dh, auth.
--   - Configuración del sistema: agregar tabla configuracion_sistema para
--     parámetros del mapa (centro, zoom, colores de pines) actualmente en localStorage.
-- ============================================================================
-- ============================================================================
-- BLOQUE 9: CONFIGURACIONES DEL SISTEMA
-- ============================================================================

create table public.configuracion (
    clave                   text primary key,
    valor                   jsonb not null default '{}'::jsonb,
    descripcion             text,
    updated_at              timestamptz not null default now()
);

create table public.configuracion_smtp (
    id                      smallint primary key default 1,
    host                    text not null,
    port                    integer not null default 587,
    usuario                 text not null,
    password_encriptada     text not null,
    requiere_tls            boolean not null default true,
    remitente_email         text not null,
    remitente_nombre        text not null,
    updated_at              timestamptz not null default now(),
    check (id = 1) -- Ensure only one row exists
);

-- ============================================================================
-- BLOQUE 10: NOTIFICACIONES
-- ============================================================================

create table public.notificaciones (
    id                      bigint generated always as identity primary key,
    titulo                  text not null,
    mensaje                 text not null,
    tipo                    text not null default 'info',
    prioridad               text not null default 'media',
    leida                   boolean not null default false,
    datos                   jsonb,
    origen                  text not null default 'sistema',
    usuario_id              uuid references public.usuarios(id),
    created_at              timestamptz not null default now()
);
