-- ============================================================================
-- CENTRO DE MONITOREO SSSUR
-- Esquema normalizado v2 para Supabase/PostgreSQL/PostGIS
-- Enfoque: sistema interno (empleados/admin) con apertura futura a ciudadanía.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. EXTENSIONES
-- ----------------------------------------------------------------------------
create extension if not exists "pgcrypto";
create extension if not exists "postgis";
create extension if not exists "citext";

-- ----------------------------------------------------------------------------
-- 1. TERRITORIO Y ESTRUCTURA ADMINISTRATIVA
-- ----------------------------------------------------------------------------
create table public.municipios (
    id          smallint generated by default as identity primary key,
    codigo      text not null unique,
    nombre      text not null unique,
    activo      boolean not null default true,
    created_at  timestamptz not null default now()
);

create table public.distritos (
    id            smallint generated by default as identity primary key,
    municipio_id  smallint not null references public.municipios(id),
    codigo        text not null,
    nombre        text not null,
    activo        boolean not null default true,
    created_at    timestamptz not null default now(),
    unique (municipio_id, codigo),
    unique (municipio_id, nombre)
);

create table public.direcciones_administrativas (
    id          bigint generated always as identity primary key,
    codigo      text not null unique,
    nombre      text not null unique,
    activo      boolean not null default true,
    created_at  timestamptz not null default now()
);

create table public.departamentos (
    id              bigint generated always as identity primary key,
    direccion_id    bigint not null references public.direcciones_administrativas(id),
    codigo          text not null unique,
    nombre          text not null,
    estado          text not null default 'activo' check (estado in ('activo', 'inactivo')),
    created_at      timestamptz not null default now(),
    unique (direccion_id, nombre)
);

-- ----------------------------------------------------------------------------
-- 2. SEGURIDAD: ROLES, PERMISOS Y USUARIOS
-- ----------------------------------------------------------------------------
create table public.roles (
    id            bigint generated always as identity primary key,
    codigo        text not null unique,
    nombre        text not null unique,
    descripcion   text,
    es_sistema    boolean not null default true,
    activo        boolean not null default true,
    created_at    timestamptz not null default now()
);

create table public.permisos (
    id            bigint generated always as identity primary key,
    codigo        text not null unique,
    nombre        text not null,
    modulo        text not null,
    descripcion   text,
    activo        boolean not null default true,
    created_at    timestamptz not null default now()
);

create table public.roles_permisos (
    rol_id        bigint not null references public.roles(id) on delete cascade,
    permiso_id    bigint not null references public.permisos(id) on delete cascade,
    created_at    timestamptz not null default now(),
    primary key (rol_id, permiso_id)
);

create table public.usuarios (
    id                  uuid primary key references auth.users(id) on delete cascade,
    username            citext unique,
    email_institucional citext unique,
    nombres             text not null,
    apellidos           text not null,
    telefono            text,
    departamento_id     bigint references public.departamentos(id),
    distrito_id         smallint references public.distritos(id),
    activo              boolean not null default true,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

create table public.usuarios_roles (
    usuario_id     uuid not null references public.usuarios(id) on delete cascade,
    rol_id         bigint not null references public.roles(id) on delete restrict,
    es_principal   boolean not null default false,
    assigned_at    timestamptz not null default now(),
    primary key (usuario_id, rol_id)
);

create unique index uq_usuarios_roles_principal
on public.usuarios_roles (usuario_id)
where es_principal = true;

create table public.cuadrillas (
    id               bigint generated always as identity primary key,
    departamento_id  bigint not null references public.departamentos(id),
    codigo           text not null unique,
    nombre           text not null,
    activo           boolean not null default true,
    created_at       timestamptz not null default now()
);

create table public.cuadrilla_miembros (
    cuadrilla_id     bigint not null references public.cuadrillas(id) on delete cascade,
    usuario_id       uuid not null references public.usuarios(id) on delete cascade,
    cargo            text,
    es_jefe          boolean not null default false,
    assigned_at      timestamptz not null default now(),
    primary key (cuadrilla_id, usuario_id)
);

-- ----------------------------------------------------------------------------
-- 3. CATÁLOGOS OPERATIVOS
-- ----------------------------------------------------------------------------
create table public.prioridades (
    id                      smallint primary key,
    codigo                  text not null unique,
    nombre                  text not null,
    nivel                   smallint not null unique check (nivel between 1 and 5),
    color_hex               text,
    tiempo_objetivo_horas   integer
);

create table public.estados_denuncia (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    orden       smallint not null unique,
    es_final    boolean not null default false
);

create table public.estados_incidente (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    orden       smallint not null unique,
    es_final    boolean not null default false
);

create table public.estados_intervencion (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    orden       smallint not null unique,
    es_final    boolean not null default false
);

create table public.canales_reporte (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    activo      boolean not null default true
);

create table public.tipos_incidente (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    activo      boolean not null default true
);

create table public.tipos_intervencion (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    activo      boolean not null default true
);

create table public.tipos_reporte (
    id          smallint primary key,
    codigo      text not null unique,
    nombre      text not null,
    descripcion text,
    activo      boolean not null default true
);

create table public.tipos_documento (
    id              smallint primary key,
    codigo          text not null unique,
    nombre          text not null,
    entidad_base    text not null check (entidad_base in ('denuncia', 'incidente', 'intervencion', 'reporte')),
    activo          boolean not null default true
);

create table public.categorias_denuncia (
    id                           bigint generated always as identity primary key,
    codigo                       text not null unique,
    nombre                       text not null unique,
    descripcion                  text,
    icono                        text,
    color_hex                    text,
    departamento_responsable_id  bigint not null references public.departamentos(id),
    activo                       boolean not null default true,
    created_at                   timestamptz not null default now()
);

create table public.subcategorias_denuncia (
    id                    bigint generated always as identity primary key,
    categoria_id          bigint not null references public.categorias_denuncia(id) on delete cascade,
    codigo                text not null unique,
    nombre                text not null,
    descripcion           text,
    prioridad_default_id  smallint references public.prioridades(id),
    activo                boolean not null default true,
    created_at            timestamptz not null default now(),
    unique (categoria_id, nombre),
    unique (categoria_id, id)
);

-- ----------------------------------------------------------------------------
-- 4. REPORTANTES, DENUNCIAS E HISTORIAL
-- ----------------------------------------------------------------------------
create table public.reportantes (
    id               bigint generated always as identity primary key,
    tipo_persona     text not null check (tipo_persona in ('ciudadano', 'institucion', 'anonimo')),
    nombres          text,
    apellidos        text,
    telefono         text,
    email            citext,
    dui              text,
    direccion_texto  text,
    distrito_id      smallint references public.distritos(id),
    activo           boolean not null default true,
    created_at       timestamptz not null default now()
);

create table public.denuncias (
    id                      bigint generated always as identity primary key,
    categoria_id            bigint not null references public.categorias_denuncia(id),
    subcategoria_id         bigint,
    distrito_id             smallint not null references public.distritos(id),
    reportante_id           bigint references public.reportantes(id),
    creada_por_usuario_id   uuid references public.usuarios(id),
    canal_reporte_id        smallint not null references public.canales_reporte(id),
    departamento_actual_id  bigint not null references public.departamentos(id),
    usuario_asignado_id     uuid references public.usuarios(id),
    cuadrilla_asignada_id   bigint references public.cuadrillas(id),
    estado_id               smallint not null references public.estados_denuncia(id),
    prioridad_id            smallint not null references public.prioridades(id),
    titulo                  text not null,
    descripcion             text not null check (char_length(descripcion) between 10 and 2000),
    direccion_referencia    text not null check (char_length(direccion_referencia) between 5 and 300),
    ubicacion               geography(Point, 4326) not null,
    fecha_ocurrencia        timestamptz,
    fecha_cierre            timestamptz,
    requiere_seguimiento    boolean not null default true,
    observaciones_internas  text,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now(),
    deleted_at              timestamptz,
    foreign key (categoria_id, subcategoria_id)
        references public.subcategorias_denuncia (categoria_id, id),
    constraint ck_denuncias_bbox_sssur check (
        st_y(ubicacion::geometry) between 13.60 and 13.80
        and st_x(ubicacion::geometry) between -89.30 and -89.10
    )
);

create index idx_denuncias_distrito on public.denuncias (distrito_id);
create index idx_denuncias_departamento on public.denuncias (departamento_actual_id);
create index idx_denuncias_estado on public.denuncias (estado_id);
create index idx_denuncias_prioridad on public.denuncias (prioridad_id);
create index idx_denuncias_usuario_asignado on public.denuncias (usuario_asignado_id);
create index idx_denuncias_cuadrilla_asignada on public.denuncias (cuadrilla_asignada_id);
create index idx_denuncias_created_at on public.denuncias (created_at desc);
create index idx_denuncias_ubicacion on public.denuncias using gist (ubicacion);

create table public.denuncias_adjuntos (
    id               bigint generated always as identity primary key,
    denuncia_id      bigint not null references public.denuncias(id) on delete cascade,
    tipo_archivo     text not null check (tipo_archivo in ('foto', 'video', 'audio', 'documento')),
    url_archivo      text not null,
    nombre_archivo   text,
    mime_type        text,
    tamano_bytes     bigint,
    hash_sha256      text,
    created_at       timestamptz not null default now()
);

create table public.denuncias_derivaciones (
    id                        bigint generated always as identity primary key,
    denuncia_id               bigint not null references public.denuncias(id) on delete cascade,
    departamento_origen_id    bigint references public.departamentos(id),
    departamento_destino_id   bigint not null references public.departamentos(id),
    motivo                    text,
    derivada_por_usuario_id   uuid not null references public.usuarios(id),
    created_at                timestamptz not null default now()
);

create table public.historial_estados_denuncia (
    id                      bigint generated always as identity primary key,
    denuncia_id             bigint not null references public.denuncias(id) on delete cascade,
    estado_id               smallint not null references public.estados_denuncia(id),
    cambiado_por_usuario_id uuid references public.usuarios(id),
    observacion             text,
    created_at              timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 5. INCIDENTES E INTERVENCIONES
-- ----------------------------------------------------------------------------
create table public.incidentes (
    id                          bigint generated always as identity primary key,
    denuncia_id                 bigint references public.denuncias(id) on delete set null,
    tipo_incidente_id           smallint not null references public.tipos_incidente(id),
    distrito_id                 smallint not null references public.distritos(id),
    departamento_responsable_id bigint not null references public.departamentos(id),
    estado_id                   smallint not null references public.estados_incidente(id),
    prioridad_id                smallint not null references public.prioridades(id),
    creado_por_usuario_id       uuid references public.usuarios(id),
    titulo                      text not null,
    descripcion                 text,
    ubicacion                   geography(Point, 4326),
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now(),
    cerrado_at                  timestamptz
);

create index idx_incidentes_distrito on public.incidentes (distrito_id);
create index idx_incidentes_departamento on public.incidentes (departamento_responsable_id);
create index idx_incidentes_estado on public.incidentes (estado_id);
create index idx_incidentes_created_at on public.incidentes (created_at desc);
create index idx_incidentes_ubicacion on public.incidentes using gist (ubicacion);

create table public.historial_estados_incidente (
    id                      bigint generated always as identity primary key,
    incidente_id            bigint not null references public.incidentes(id) on delete cascade,
    estado_id               smallint not null references public.estados_incidente(id),
    cambiado_por_usuario_id uuid references public.usuarios(id),
    observacion             text,
    created_at              timestamptz not null default now()
);

create table public.intervenciones (
    id                     bigint generated always as identity primary key,
    incidente_id           bigint not null references public.incidentes(id) on delete cascade,
    tipo_intervencion_id   smallint not null references public.tipos_intervencion(id),
    estado_id              smallint not null references public.estados_intervencion(id),
    cuadrilla_id           bigint references public.cuadrillas(id),
    responsable_usuario_id uuid references public.usuarios(id),
    programada_para        timestamptz,
    iniciada_en            timestamptz,
    finalizada_en          timestamptz,
    geometria              geometry(Geometry, 4326),
    resumen_resultado      text,
    created_at             timestamptz not null default now(),
    updated_at             timestamptz not null default now()
);

create index idx_intervenciones_incidente on public.intervenciones (incidente_id);
create index idx_intervenciones_estado on public.intervenciones (estado_id);
create index idx_intervenciones_cuadrilla on public.intervenciones (cuadrilla_id);
create index idx_intervenciones_geometria on public.intervenciones using gist (geometria);

create table public.historial_estados_intervencion (
    id                      bigint generated always as identity primary key,
    intervencion_id         bigint not null references public.intervenciones(id) on delete cascade,
    estado_id               smallint not null references public.estados_intervencion(id),
    cambiado_por_usuario_id uuid references public.usuarios(id),
    observacion             text,
    created_at              timestamptz not null default now()
);

create table public.intervenciones_evidencias (
    id               bigint generated always as identity primary key,
    intervencion_id  bigint not null references public.intervenciones(id) on delete cascade,
    tipo_archivo     text not null check (tipo_archivo in ('foto', 'video', 'audio', 'documento')),
    url_archivo      text not null,
    nombre_archivo   text,
    mime_type        text,
    tamano_bytes     bigint,
    hash_sha256      text,
    created_at       timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 6. REPORTES, COMPROBANTES Y GESTOR DE PLANTILLAS
-- ----------------------------------------------------------------------------
create table public.plantillas_documento (
    id               bigint generated always as identity primary key,
    tipo_documento_id smallint not null references public.tipos_documento(id),
    codigo           text not null unique,
    nombre           text not null,
    entidad_objetivo text not null check (entidad_objetivo in ('denuncia', 'incidente', 'intervencion', 'reporte')),
    motor_render     text not null default 'html',
    descripcion      text,
    activa           boolean not null default true,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

create table public.plantillas_documento_versiones (
    id                    bigint generated always as identity primary key,
    plantilla_id          bigint not null references public.plantillas_documento(id) on delete cascade,
    version_num           integer not null,
    es_vigente            boolean not null default false,
    contenido_html        text not null,
    hoja_estilos          text,
    esquema_variables     jsonb,
    creado_por_usuario_id uuid references public.usuarios(id),
    created_at            timestamptz not null default now(),
    unique (plantilla_id, version_num)
);

create unique index uq_plantilla_version_vigente
on public.plantillas_documento_versiones (plantilla_id)
where es_vigente = true;

create table public.reportes_emitidos (
    id                      bigint generated always as identity primary key,
    tipo_reporte_id         smallint not null references public.tipos_reporte(id),
    plantilla_version_id    bigint references public.plantillas_documento_versiones(id),
    generado_por_usuario_id uuid not null references public.usuarios(id),
    nombre_archivo          text not null,
    formato_salida          text not null check (formato_salida in ('pdf', 'xlsx', 'csv', 'html')),
    parametros              jsonb not null default '{}'::jsonb,
    rango_desde             date,
    rango_hasta             date,
    total_registros         integer,
    url_archivo             text,
    hash_sha256             text,
    created_at              timestamptz not null default now()
);

create index idx_reportes_emitidos_tipo on public.reportes_emitidos (tipo_reporte_id);
create index idx_reportes_emitidos_usuario on public.reportes_emitidos (generado_por_usuario_id);
create index idx_reportes_emitidos_fecha on public.reportes_emitidos (created_at desc);

create table public.documentos_generados (
    id                      bigint generated always as identity primary key,
    plantilla_version_id    bigint references public.plantillas_documento_versiones(id),
    tipo_documento_id       smallint not null references public.tipos_documento(id),
    entidad_tipo            text not null check (entidad_tipo in ('denuncia', 'incidente', 'intervencion')),
    entidad_id              bigint not null,
    generado_por_usuario_id uuid references public.usuarios(id),
    nombre_archivo          text not null,
    formato_salida          text not null check (formato_salida in ('pdf', 'html')),
    url_archivo             text,
    metadatos               jsonb not null default '{}'::jsonb,
    created_at              timestamptz not null default now()
);

create index idx_documentos_generados_entidad
on public.documentos_generados (entidad_tipo, entidad_id);

-- ----------------------------------------------------------------------------
-- 7. AUDITORÍA Y HELPERS
-- ----------------------------------------------------------------------------
create table public.bitacora_auditoria (
    id              bigint generated always as identity primary key,
    usuario_id      uuid references public.usuarios(id),
    accion          text not null,
    tabla_afectada  text not null,
    registro_id     text,
    detalle         jsonb,
    created_at      timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.sincronizar_departamento_denuncia()
returns trigger
language plpgsql
as $$
begin
    if new.departamento_actual_id is null then
        select c.departamento_responsable_id
        into new.departamento_actual_id
        from public.categorias_denuncia c
        where c.id = new.categoria_id;
    end if;

    if new.estado_id is null then
        select id into new.estado_id
        from public.estados_denuncia
        where codigo = 'pendiente'
        limit 1;
    end if;

    return new;
end;
$$;

create or replace function public.aplicar_derivacion_denuncia()
returns trigger
language plpgsql
as $$
begin
    update public.denuncias
    set departamento_actual_id = new.departamento_destino_id,
        updated_at = now()
    where id = new.denuncia_id;

    return new;
end;
$$;

create or replace function public.registrar_auditoria()
returns trigger
language plpgsql
security definer
as $$
begin
    insert into public.bitacora_auditoria (usuario_id, accion, tabla_afectada, registro_id, detalle)
    values (
        auth.uid(),
        TG_OP,
        TG_TABLE_NAME,
        coalesce(new.id, old.id)::text,
        case
            when TG_OP = 'DELETE' then to_jsonb(old)
            else to_jsonb(new)
        end
    );

    return coalesce(new, old);
end;
$$;

create or replace function public.auth_tiene_rol(p_rol_codigo text)
returns boolean
language sql
security definer
stable
as $$
    select exists (
        select 1
        from public.usuarios_roles ur
        join public.roles r on r.id = ur.rol_id
        join public.usuarios u on u.id = ur.usuario_id
        where ur.usuario_id = auth.uid()
          and u.activo = true
          and r.activo = true
          and r.codigo = p_rol_codigo
    );
$$;

create or replace function public.auth_tiene_permiso(p_permiso_codigo text)
returns boolean
language sql
security definer
stable
as $$
    select exists (
        select 1
        from public.usuarios_roles ur
        join public.roles r on r.id = ur.rol_id
        join public.roles_permisos rp on rp.rol_id = r.id
        join public.permisos p on p.id = rp.permiso_id
        join public.usuarios u on u.id = ur.usuario_id
        where ur.usuario_id = auth.uid()
          and u.activo = true
          and r.activo = true
          and p.activo = true
          and p.codigo = p_permiso_codigo
    );
$$;

create view public.v_denuncias_mapa as
select
    d.id,
    d.titulo,
    d.descripcion,
    d.direccion_referencia,
    d.distrito_id,
    di.nombre as distrito_nombre,
    d.estado_id,
    ed.codigo as estado_codigo,
    ed.nombre as estado_nombre,
    d.prioridad_id,
    pr.nombre as prioridad_nombre,
    d.categoria_id,
    cd.nombre as categoria_nombre,
    d.subcategoria_id,
    sd.nombre as subcategoria_nombre,
    d.departamento_actual_id,
    dep.nombre as departamento_actual_nombre,
    st_y(d.ubicacion::geometry) as lat,
    st_x(d.ubicacion::geometry) as lng,
    d.created_at
from public.denuncias d
join public.distritos di on di.id = d.distrito_id
join public.estados_denuncia ed on ed.id = d.estado_id
join public.prioridades pr on pr.id = d.prioridad_id
join public.categorias_denuncia cd on cd.id = d.categoria_id
left join public.subcategorias_denuncia sd on sd.id = d.subcategoria_id
join public.departamentos dep on dep.id = d.departamento_actual_id;

-- ----------------------------------------------------------------------------
-- 8. TRIGGERS
-- ----------------------------------------------------------------------------
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row execute function public.set_updated_at();

create trigger trg_denuncias_updated_at
before update on public.denuncias
for each row execute function public.set_updated_at();

create trigger trg_denuncias_sync_departamento
before insert on public.denuncias
for each row execute function public.sincronizar_departamento_denuncia();

create trigger trg_incidentes_updated_at
before update on public.incidentes
for each row execute function public.set_updated_at();

create trigger trg_intervenciones_updated_at
before update on public.intervenciones
for each row execute function public.set_updated_at();

create trigger trg_plantillas_updated_at
before update on public.plantillas_documento
for each row execute function public.set_updated_at();

create trigger trg_derivaciones_denuncia
after insert on public.denuncias_derivaciones
for each row execute function public.aplicar_derivacion_denuncia();

create trigger trg_auditoria_denuncias
after insert or update or delete on public.denuncias
for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_incidentes
after insert or update or delete on public.incidentes
for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_intervenciones
after insert or update or delete on public.intervenciones
for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_reportes
after insert or update or delete on public.reportes_emitidos
for each row execute function public.registrar_auditoria();

create trigger trg_auditoria_plantillas_versiones
after insert or update or delete on public.plantillas_documento_versiones
for each row execute function public.registrar_auditoria();

-- ----------------------------------------------------------------------------
-- 9. RLS BASE
-- ----------------------------------------------------------------------------
alter table public.roles enable row level security;
alter table public.permisos enable row level security;
alter table public.roles_permisos enable row level security;
alter table public.usuarios enable row level security;
alter table public.usuarios_roles enable row level security;
alter table public.cuadrillas enable row level security;
alter table public.cuadrilla_miembros enable row level security;
alter table public.municipios enable row level security;
alter table public.distritos enable row level security;
alter table public.direcciones_administrativas enable row level security;
alter table public.departamentos enable row level security;
alter table public.prioridades enable row level security;
alter table public.estados_denuncia enable row level security;
alter table public.estados_incidente enable row level security;
alter table public.estados_intervencion enable row level security;
alter table public.canales_reporte enable row level security;
alter table public.tipos_incidente enable row level security;
alter table public.tipos_intervencion enable row level security;
alter table public.tipos_reporte enable row level security;
alter table public.tipos_documento enable row level security;
alter table public.categorias_denuncia enable row level security;
alter table public.subcategorias_denuncia enable row level security;
alter table public.reportantes enable row level security;
alter table public.denuncias enable row level security;
alter table public.denuncias_adjuntos enable row level security;
alter table public.denuncias_derivaciones enable row level security;
alter table public.historial_estados_denuncia enable row level security;
alter table public.incidentes enable row level security;
alter table public.historial_estados_incidente enable row level security;
alter table public.intervenciones enable row level security;
alter table public.historial_estados_intervencion enable row level security;
alter table public.intervenciones_evidencias enable row level security;
alter table public.plantillas_documento enable row level security;
alter table public.plantillas_documento_versiones enable row level security;
alter table public.reportes_emitidos enable row level security;
alter table public.documentos_generados enable row level security;
alter table public.bitacora_auditoria enable row level security;

-- Catálogos operativos: lectura autenticada, administración por rol admin.
create policy "catalogos_select_autenticados_roles"
on public.roles for select to authenticated using (true);

create policy "catalogos_select_autenticados_permisos"
on public.permisos for select to authenticated using (true);

create policy "catalogos_select_autenticados_roles_permisos"
on public.roles_permisos for select to authenticated using (true);

create policy "catalogos_select_autenticados_territorio_1"
on public.municipios for select to authenticated using (true);

create policy "catalogos_select_autenticados_territorio_2"
on public.distritos for select to authenticated using (true);

create policy "catalogos_select_autenticados_estructura_1"
on public.direcciones_administrativas for select to authenticated using (true);

create policy "catalogos_select_autenticados_estructura_2"
on public.departamentos for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_1"
on public.prioridades for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_2"
on public.estados_denuncia for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_3"
on public.estados_incidente for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_4"
on public.estados_intervencion for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_5"
on public.canales_reporte for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_6"
on public.tipos_incidente for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_7"
on public.tipos_intervencion for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_8"
on public.tipos_reporte for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_9"
on public.tipos_documento for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_10"
on public.categorias_denuncia for select to authenticated using (true);

create policy "catalogos_select_autenticados_operativos_11"
on public.subcategorias_denuncia for select to authenticated using (true);

create policy "usuarios_select_propio_o_admin"
on public.usuarios for select to authenticated
using (id = auth.uid() or public.auth_tiene_rol('admin'));

create policy "usuarios_update_propio_o_admin"
on public.usuarios for update to authenticated
using (id = auth.uid() or public.auth_tiene_rol('admin'))
with check (id = auth.uid() or public.auth_tiene_rol('admin'));

create policy "usuarios_roles_select_propio_o_admin"
on public.usuarios_roles for select to authenticated
using (usuario_id = auth.uid() or public.auth_tiene_rol('admin'));

create policy "usuarios_insert_admin"
on public.usuarios for insert to authenticated
with check (public.auth_tiene_rol('admin'));

create policy "usuarios_roles_admin_full"
on public.usuarios_roles for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "cuadrillas_select_por_permiso"
on public.cuadrillas for select to authenticated
using (public.auth_tiene_permiso('intervenciones.ver') or public.auth_tiene_rol('admin'));

create policy "cuadrillas_admin_full"
on public.cuadrillas for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "cuadrilla_miembros_select_por_permiso"
on public.cuadrilla_miembros for select to authenticated
using (public.auth_tiene_permiso('intervenciones.ver') or public.auth_tiene_rol('admin'));

create policy "cuadrilla_miembros_admin_full"
on public.cuadrilla_miembros for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_1"
on public.roles for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_2"
on public.permisos for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_3"
on public.roles_permisos for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_4"
on public.direcciones_administrativas for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_5"
on public.departamentos for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_6"
on public.municipios for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_estructura_7"
on public.distritos for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_1"
on public.prioridades for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_2"
on public.estados_denuncia for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_3"
on public.estados_incidente for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_4"
on public.estados_intervencion for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_5"
on public.canales_reporte for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_6"
on public.tipos_incidente for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_7"
on public.tipos_intervencion for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_8"
on public.tipos_reporte for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_9"
on public.tipos_documento for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_10"
on public.categorias_denuncia for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "catalogos_admin_operativos_11"
on public.subcategorias_denuncia for all to authenticated
using (public.auth_tiene_rol('admin'))
with check (public.auth_tiene_rol('admin'));

create policy "reportantes_select_por_permiso"
on public.reportantes for select to authenticated
using (public.auth_tiene_permiso('denuncias.ver') or public.auth_tiene_rol('admin'));

create policy "reportantes_write_por_permiso"
on public.reportantes for all to authenticated
using (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'));

create policy "denuncias_select_por_permiso"
on public.denuncias for select to authenticated
using (public.auth_tiene_permiso('denuncias.ver') or public.auth_tiene_rol('admin'));

create policy "denuncias_insert_por_permiso"
on public.denuncias for insert to authenticated
with check (public.auth_tiene_permiso('denuncias.crear') or public.auth_tiene_rol('admin'));

create policy "denuncias_update_por_permiso"
on public.denuncias for update to authenticated
using (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'));

create policy "denuncias_adjuntos_select_por_permiso"
on public.denuncias_adjuntos for select to authenticated
using (public.auth_tiene_permiso('denuncias.ver') or public.auth_tiene_rol('admin'));

create policy "denuncias_adjuntos_write_por_permiso"
on public.denuncias_adjuntos for all to authenticated
using (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'));

create policy "denuncias_derivaciones_select_por_permiso"
on public.denuncias_derivaciones for select to authenticated
using (public.auth_tiene_permiso('denuncias.ver') or public.auth_tiene_rol('admin'));

create policy "denuncias_derivaciones_write_por_permiso"
on public.denuncias_derivaciones for all to authenticated
using (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'));

create policy "historial_denuncias_select_por_permiso"
on public.historial_estados_denuncia for select to authenticated
using (public.auth_tiene_permiso('denuncias.ver') or public.auth_tiene_rol('admin'));

create policy "historial_denuncias_write_por_permiso"
on public.historial_estados_denuncia for all to authenticated
using (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('denuncias.editar') or public.auth_tiene_rol('admin'));

create policy "incidentes_select_por_permiso"
on public.incidentes for select to authenticated
using (public.auth_tiene_permiso('incidentes.ver') or public.auth_tiene_rol('admin'));

create policy "incidentes_write_por_permiso"
on public.incidentes for all to authenticated
using (public.auth_tiene_permiso('incidentes.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('incidentes.gestionar') or public.auth_tiene_rol('admin'));

create policy "historial_incidentes_select_por_permiso"
on public.historial_estados_incidente for select to authenticated
using (public.auth_tiene_permiso('incidentes.ver') or public.auth_tiene_rol('admin'));

create policy "historial_incidentes_write_por_permiso"
on public.historial_estados_incidente for all to authenticated
using (public.auth_tiene_permiso('incidentes.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('incidentes.gestionar') or public.auth_tiene_rol('admin'));

create policy "intervenciones_select_por_permiso"
on public.intervenciones for select to authenticated
using (public.auth_tiene_permiso('intervenciones.ver') or public.auth_tiene_rol('admin'));

create policy "intervenciones_write_por_permiso"
on public.intervenciones for all to authenticated
using (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'));

create policy "historial_intervenciones_select_por_permiso"
on public.historial_estados_intervencion for select to authenticated
using (public.auth_tiene_permiso('intervenciones.ver') or public.auth_tiene_rol('admin'));

create policy "historial_intervenciones_write_por_permiso"
on public.historial_estados_intervencion for all to authenticated
using (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'));

create policy "intervenciones_evidencias_select_por_permiso"
on public.intervenciones_evidencias for select to authenticated
using (public.auth_tiene_permiso('intervenciones.ver') or public.auth_tiene_rol('admin'));

create policy "intervenciones_evidencias_write_por_permiso"
on public.intervenciones_evidencias for all to authenticated
using (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('intervenciones.gestionar') or public.auth_tiene_rol('admin'));

create policy "reportes_select_propios_o_permiso"
on public.reportes_emitidos for select to authenticated
using (
    generado_por_usuario_id = auth.uid()
    or public.auth_tiene_permiso('reportes.ver')
    or public.auth_tiene_rol('admin')
);

create policy "reportes_insert_por_permiso"
on public.reportes_emitidos for insert to authenticated
with check (public.auth_tiene_permiso('reportes.generar') or public.auth_tiene_rol('admin'));

create policy "documentos_generados_select_por_permiso"
on public.documentos_generados for select to authenticated
using (
    generado_por_usuario_id = auth.uid()
    or public.auth_tiene_permiso('reportes.ver')
    or public.auth_tiene_rol('admin')
);

create policy "documentos_generados_write_por_permiso"
on public.documentos_generados for all to authenticated
using (
    public.auth_tiene_permiso('reportes.generar')
    or public.auth_tiene_permiso('plantillas.gestionar')
    or public.auth_tiene_rol('admin')
)
with check (
    public.auth_tiene_permiso('reportes.generar')
    or public.auth_tiene_permiso('plantillas.gestionar')
    or public.auth_tiene_rol('admin')
);

create policy "plantillas_select_por_permiso"
on public.plantillas_documento for select to authenticated
using (public.auth_tiene_permiso('plantillas.ver') or public.auth_tiene_rol('admin'));

create policy "plantillas_write_por_permiso"
on public.plantillas_documento for all to authenticated
using (public.auth_tiene_permiso('plantillas.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('plantillas.gestionar') or public.auth_tiene_rol('admin'));

create policy "plantillas_versiones_select_por_permiso"
on public.plantillas_documento_versiones for select to authenticated
using (public.auth_tiene_permiso('plantillas.ver') or public.auth_tiene_rol('admin'));

create policy "plantillas_versiones_write_por_permiso"
on public.plantillas_documento_versiones for all to authenticated
using (public.auth_tiene_permiso('plantillas.gestionar') or public.auth_tiene_rol('admin'))
with check (public.auth_tiene_permiso('plantillas.gestionar') or public.auth_tiene_rol('admin'));

create policy "auditoria_select_admin"
on public.bitacora_auditoria for select to authenticated
using (public.auth_tiene_rol('admin'));

-- ----------------------------------------------------------------------------
-- FIN
-- Nota:
-- 1. El portal ciudadano futuro puede exponer RPC/Edge Functions sobre reportantes
--    y denuncias sin romper este modelo.
-- 2. Los CSV actuales deben cargarse a direcciones/departamentos y
--    categorias/subcategorias, no a textos libres.
-- ----------------------------------------------------------------------------
